### ISSUE TITLE
Outline Script Causing Errors On Play

### ISSUE THREAD

**Issue by Aegistus** [Aegistus/Untitled-Pirate-Game#62]
Getting a string of errors when Outline scripts are attached to Ship Objects. Outlines have been removed for time-being. Here is an example exception message:

Not allowed to access vertices on mesh 'SM_Veh_Boat_Warship_01_Hull_Bare' (isReadable is false; Read/Write must be enabled in import settings)
UnityEngine.Mesh:get_vertices ()
Outline:SmoothNormals (UnityEngine.Mesh) (at Assets/Prefabs/FX/Outline/Outline.cs:218)
Outline:LoadSmoothNormals () (at Assets/Prefabs/FX/Outline/Outline.cs:186)
Outline:Awake () (at Assets/Prefabs/FX/Outline/Outline.cs:90)
UnityEngine.Object:Instantiate<UnityEngine.GameObject> (UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion)
EnemySpawner:SpawnEnemy () (at Assets/Scripts/Level Objects/EnemySpawner.cs:17)
SpawnManager/<SpawnEnemies>d__4:MoveNext () (at Assets/Scripts/Level Objects/SpawnManager.cs:34)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by JinNada** [comment]
The new boats were not imported with read/write perms on so they threw errors at the Outline and Spawner scripts.  Fixed perms & reimplemented Outlines.
